# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-18 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'achievement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkelement',
            fields=[
                ('id_check_element', models.IntegerField(primary_key=True, serialize=False)),
                ('element_name', models.CharField(blank=True, max_length=255, null=True)),
                ('element_cost', models.FloatField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checkelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('id_check', models.IntegerField(primary_key=True, serialize=False)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('total_cost', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'checks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Debtelement',
            fields=[
                ('id_dept_element', models.IntegerField(primary_key=True, serialize=False)),
                ('value_dept', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'debtelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dictachievement',
            fields=[
                ('id_dict_achievement', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('target_value', models.IntegerField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'dictachievement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id_friend', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_registred', models.NullBooleanField()),
            ],
            options={
                'db_table': 'friend',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usercheckelement',
            fields=[
                ('id_user_check_element', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usercheckelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_registration', models.DateField(blank=True, null=True)),
                ('password_user', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
