# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 23:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_value', models.DecimalField(decimal_places=4, max_digits=5)),
                ('date_achieved', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(null=True)),
                ('image_url', models.ImageField(max_length=255, null=True, upload_to=b'')),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CheckElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='DebtElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_debt', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='DictAchievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=255)),
                ('target_value', models.IntegerField()),
                ('image_path', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=1)),
                ('date_changed', models.DateField()),
                ('fk_user_friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_friend', to=settings.AUTH_USER_MODEL)),
                ('fk_user_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_check', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCheckElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=4, max_digits=5)),
                ('fk_check_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user', to='BillSays.CheckElement')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Waitress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='BillSays.Check')),
                ('comment', models.CharField(max_length=500)),
                ('waitress_rate', models.IntegerField()),
                ('food_rate', models.IntegerField()),
                ('atmosphere_rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='fk_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_owner', to='BillSays.Owner'),
        ),
        migrations.AddField(
            model_name='debtelement',
            name='fk_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_debt_friend', to='BillSays.Friend'),
        ),
        migrations.AddField(
            model_name='debtelement',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_user_debt_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checkelement',
            name='fk_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_check', to='BillSays.Check'),
        ),
        migrations.AddField(
            model_name='check',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='check',
            name='fk_waitress',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='BillSays.Waitress'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='fk_dict_achievement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dict_achievement', to='BillSays.DictAchievement'),
        ),
        migrations.AddField(
            model_name='achievement',
            name='fk_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
